rodney:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20  

  # Position Controllers ---------------------------------------
  joint_pan_position_controller:
    type: effort_controllers/JointPositionController
    joint: head_pan
    pid: {p: 1.0, i: 0.01, d: 0.0}
    
  joint_tilt_position_controller:
    type: effort_controllers/JointPositionController
    joint: head_tilt
    pid: {p: 1.0, i: 0.01, d: 0.0}
